
services:
  # User Service
  user-service:
    build: ./services/user
    container_name: user-service
    environment:
      - PORT=5000
      - JWT_SEC=sdcmmksck
      - Cloud_Name=dwn4dsa7z
      - Cloud_Api_Key=594691339365792
      - Cloud_Api_Secret=EgxqhrN4LoKy8aXBdhLADvgK5Uk
      - MONGO_URI=mongodb+srv://raishivansh9848:Rq3Q766cAVtpPZCG@cluster0.mlybktv.mongodb.net/
      - Google_Client_id=979430820874-gl4lub7pp6v9fp8j61870ehcg0fvoakn.apps.googleusercontent.com
      - Google_client_secret=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
    ports:
      - "5000:5000"

  # Author Service
  author-service:
    build: ./services/author
    container_name: author-service
    environment:
      - PORT=5001
      - JWT_SEC=sdcmmksck
      - Cloud_Name=dwn4dsa7z
      - Cloud_Api_Key=594691339365792
      - Cloud_Api_Secret=EgxqhrN4LoKy8aXBdhLADvgK5Uk
      - Gemini_Api_Key=AIzaSyAaULUt8XKyzrEYK_ZO5_CLshghlLZUxZk
      - DB_URL=postgresql://neondb_owner:npg_jJ2KLG4hzvMq@ep-small-sun-a148lyjc-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - RABBITMQ_URL=amqps://cwuoysap:wAJP1bCQ1ngoytLQIHZMwGKuKF2rgGZn@puffin.rmq2.cloudamqp.com/cwuoysap
    ports:
      - "5001:5001"

  # Blog Service
  blog-service:
    build: ./services/blog
    container_name: blog-service
    environment:
      - PORT=5002
      - USER_SERVICE=http://user-service:5000
      - JWT_SEC=sdcmmksck
      - REDIS_URL=rediss://default:AVMqAAIjcDFhZDY3NGQ2MDM2YjU0NGRjODQ1Njg4NzAzMWUzZjViYnAxMA@close-rodent-21290.upstash.io:6379
      - DB_URL=postgresql://neondb_owner:npg_jJ2KLG4hzvMq@ep-small-sun-a148lyjc-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - RABBITMQ_URL=amqps://cwuoysap:wAJP1bCQ1ngoytLQIHZMwGKuKF2rgGZn@puffin.rmq2.cloudamqp.com/cwuoysap
    ports:
      - "5002:5002"
    depends_on:
      - user-service

  # Frontend (Next.js)
  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env.docker
    # environment:
    #   NEXT_PUBLIC_USER_SERVICE: http://user-service:5000
    #   NEXT_PUBLIC_AUTHOR_SERVICE: http://author-service:5001
    #   NEXT_PUBLIC_BLOG_SERVICE: http://blog-service:5002
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - author-service
      - blog-service

